ORG 1000h
BIEN DB "INGRESE LA FRASE A ANALIZAR:"
FBIEN DB 0
PAL DB "LA FRASE ES UN PALINDROMO"
FPAL DB 0
NPAL DB "LA FRASE NO ES UN PALINDROMO"
FNPAL DB 0

ORG 1500h
FRASE DB "AMA"
FFRASE DB 0

ORG 1600h
INI DW 0
FIN DW 0
LET DB 0

ORG 2000h
INICIO: MOV INI, OFFSET FRASE ; INICIO DEL ARREGLO
	MOV FIN, OFFSET FFRASE - 1 ; FIN DEL ARREGLO

VALINI: CMP [INI], 20h ; SE VALIDA QUE EL INI NO SE UN ESPACIO
	JNZ VALFIN
	INC INI
	
VALFIN: CMP [FIN], 20h ; SE VALIDA QUE EL FIN NO SE UN ESPACIO
	JNZ COMP
	INC FIN
	
COMP: CMP [INI], [FIN] ; SE COMPARAN LAS POSICIONES DE MEMORIA
	JZ CORRE ;  SI SON IGUALES EL ARREGLO ES PALINDROMO
	CMP [INI], [FIN] ; SE COMPARAN LOS CARACTERES
	JNZ INCOR ; SI SON DIFERENTES NO ES UN PALINDROMO
	
AUMEN: INC INI ; MODIFICA LAS VARIABLES
	DEC FIN
	JMP VALINI ; SE ENVIAN A VALIDAR DE NUEVO LOS NUEVOS VALORES
	
CORRE: MOV BX, OFFSET PAL ; SE IMPRIME EL MENSAJE DE CORRECTO
	MOV AL, OFFSET FPAL - OFFSET PAL
	INT 7
	JMP FINAL
	
INCOR: MOV BX, OFFSET NPAL ; SE IMPRIME EL MENSAJE DE INCORRECTO
	INT 7
	JMP FINAL

FINAL: HLT
END
